baseURL = 'https://ai.stanford.edu/~taidang/cheapvs/'
languageCode = 'en-us'
title = 'Accelerate Virtual Screening with Amortized Neural Search and Multi-Objective Bayesian Optimization'
theme = ["github.com/dzello/reveal-hugo"]

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
custom_theme = "css/serif.css"
enableSourceMap = true
margin = 0.1
history = true
slide_number = true